### ISSUE TITLE
Station secure ID

### ISSUE THREAD

**Issue by migraf** [PHT-Medic/station-backend#61]
Get the secure id (for acccessing the stations harbor project) from the central API and use it for interacting with harbor

**Comment by tada5hi** [comment]
The endpoint is:
`https://staging-pht.tada5hi.net/api/stations/<station-id>?fields=%2Bsecure_id`
Authentication flow is the same like in case of the train-builder e.g.

**Comment by migraf** [comment]
Get all required harbor credentials from API:
`secure_id`
`registry_project_account_name`
`registry_project_account_token`

**Comment by migraf** [comment]
`/stations/<station-id>` -> registry_project_id
`http://<api-url>/registry-projects/{registry_project_id}?fields=%2Baccount_secret`
