### ISSUE TITLE
Query available trains from central API 

### ISSUE THREAD

**Issue by migraf** [PHT-Medic/station-backend#69]
Request available trains for the station from the central API and store/update the train in the local database

**Comment by tada5hi** [comment]
- Scheme:
`https://staging-pht.tada5hi.net/api/train-stations?filter[station_id]=<id>` Replace `<id>` with station id
Example: https://staging-pht.tada5hi.net/api/train-stations?filter[station_id]=e7a42fa2-55dc-4182-8b5f-6eff2fa8b4eb

- Scheme with related train object:
`https://staging-pht.tada5hi.net/api/train-stations?filter[station_id]=<id>&include=train` Replace `<id>` with station id
Example: https://staging-pht.tada5hi.net/api/train-stations?filter[station_id]=e7a42fa2-55dc-4182-8b5f-6eff2fa8b4eb&include=train
